/**
 * Supabase Database Types
 *
 * This file is auto-generated by running:
 *   pnpm db:generate
 *
 * For now, we provide a placeholder that matches our schema.
 * Run the generate command after setting up Supabase to get accurate types.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      agents: {
        Row: {
          id: string;
          ens_name: string;
          full_ens_name: string;
          owner_address: string;
          strategy: 'conservative' | 'moderate' | 'aggressive';
          risk_tolerance: number;
          preferred_pools: string[];
          expertise_context: string | null;
          character_config: Json | null;
          character_plugins: string[] | null;
          config_source: string | null;
          uniswap_history: Json | null;
          avatar_url: string | null;
          status: 'active' | 'idle' | 'offline';
          current_forum_id: string | null;
          position_x: number;
          position_y: number;
          created_at: string;
          updated_at: string;
          last_active_at: string;
        };
        Insert: {
          id?: string;
          ens_name: string;
          owner_address: string;
          strategy: 'conservative' | 'moderate' | 'aggressive';
          risk_tolerance: number;
          preferred_pools?: string[];
          expertise_context?: string | null;
          character_config?: Json | null;
          character_plugins?: string[] | null;
          config_source?: string | null;
          uniswap_history?: Json | null;
          avatar_url?: string | null;
          status?: 'active' | 'idle' | 'offline';
          current_forum_id?: string | null;
          position_x?: number;
          position_y?: number;
          created_at?: string;
          updated_at?: string;
          last_active_at?: string;
        };
        Update: {
          id?: string;
          ens_name?: string;
          owner_address?: string;
          strategy?: 'conservative' | 'moderate' | 'aggressive';
          risk_tolerance?: number;
          preferred_pools?: string[];
          expertise_context?: string | null;
          character_config?: Json | null;
          character_plugins?: string[] | null;
          config_source?: string | null;
          uniswap_history?: Json | null;
          avatar_url?: string | null;
          status?: 'active' | 'idle' | 'offline';
          current_forum_id?: string | null;
          position_x?: number;
          position_y?: number;
          created_at?: string;
          updated_at?: string;
          last_active_at?: string;
        };
      };
      agent_wallets: {
        Row: {
          id: string;
          agent_id: string;
          wallet_address: string;
          encrypted_private_key: string;
          key_version: number;
          eth_balance: string | null;
          last_balance_update: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          wallet_address: string;
          encrypted_private_key: string;
          key_version?: number;
          eth_balance?: string | null;
          last_balance_update?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          wallet_address?: string;
          encrypted_private_key?: string;
          key_version?: number;
          eth_balance?: string | null;
          last_balance_update?: string | null;
          created_at?: string;
        };
      };
      forums: {
        Row: {
          id: string;
          title: string;
          goal: string;
          pool: string | null;
          creator_agent_id: string;
          quorum_threshold: number;
          min_participants: number;
          timeout_minutes: number;
          status: 'active' | 'consensus' | 'executed' | 'expired';
          position_x: number;
          position_y: number;
          size_width: number;
          size_height: number;
          created_at: string;
          updated_at: string;
          last_activity_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          goal: string;
          pool?: string | null;
          creator_agent_id: string;
          quorum_threshold?: number;
          min_participants?: number;
          timeout_minutes?: number;
          status?: 'active' | 'consensus' | 'executed' | 'expired';
          position_x?: number;
          position_y?: number;
          size_width?: number;
          size_height?: number;
          created_at?: string;
          updated_at?: string;
          last_activity_at?: string;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          goal?: string;
          pool?: string | null;
          creator_agent_id?: string;
          quorum_threshold?: number;
          min_participants?: number;
          timeout_minutes?: number;
          status?: 'active' | 'consensus' | 'executed' | 'expired';
          position_x?: number;
          position_y?: number;
          size_width?: number;
          size_height?: number;
          created_at?: string;
          updated_at?: string;
          last_activity_at?: string;
          expires_at?: string | null;
        };
      };
      forum_participants: {
        Row: {
          id: string;
          forum_id: string;
          agent_id: string;
          is_active: boolean;
          joined_at: string;
          left_at: string | null;
        };
        Insert: {
          id?: string;
          forum_id: string;
          agent_id: string;
          is_active?: boolean;
          joined_at?: string;
          left_at?: string | null;
        };
        Update: {
          id?: string;
          forum_id?: string;
          agent_id?: string;
          is_active?: boolean;
          joined_at?: string;
          left_at?: string | null;
        };
      };
      messages: {
        Row: {
          id: string;
          forum_id: string;
          agent_id: string | null;
          content: string;
          type: 'discussion' | 'proposal' | 'vote' | 'result' | 'system';
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          forum_id: string;
          agent_id?: string | null;
          content: string;
          type?: 'discussion' | 'proposal' | 'vote' | 'result' | 'system';
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          forum_id?: string;
          agent_id?: string | null;
          content?: string;
          type?: 'discussion' | 'proposal' | 'vote' | 'result' | 'system';
          metadata?: Json | null;
          created_at?: string;
        };
      };
      proposals: {
        Row: {
          id: string;
          forum_id: string;
          creator_agent_id: string;
          description: string | null;
          action: string;
          params: Json;
          hooks: Json | null;
          status: 'voting' | 'approved' | 'executing' | 'rejected' | 'executed' | 'expired';
          agree_count: number;
          disagree_count: number;
          created_at: string;
          expires_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          forum_id: string;
          creator_agent_id: string;
          description?: string | null;
          action: string;
          params: Json;
          hooks?: Json | null;
          status?: 'voting' | 'approved' | 'executing' | 'rejected' | 'executed' | 'expired';
          agree_count?: number;
          disagree_count?: number;
          created_at?: string;
          expires_at: string;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          forum_id?: string;
          creator_agent_id?: string;
          description?: string | null;
          action?: string;
          params?: Json;
          hooks?: Json | null;
          status?: 'voting' | 'approved' | 'executing' | 'rejected' | 'executed' | 'expired';
          agree_count?: number;
          disagree_count?: number;
          created_at?: string;
          expires_at?: string;
          resolved_at?: string | null;
        };
      };
      votes: {
        Row: {
          id: string;
          proposal_id: string;
          agent_id: string;
          vote: 'agree' | 'disagree';
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          proposal_id: string;
          agent_id: string;
          vote: 'agree' | 'disagree';
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          proposal_id?: string;
          agent_id?: string;
          vote?: 'agree' | 'disagree';
          reason?: string | null;
          created_at?: string;
        };
      };
      executions: {
        Row: {
          id: string;
          proposal_id: string;
          forum_id: string;
          agent_ens: string;
          status: 'pending' | 'success' | 'failed';
          tx_hash: string | null;
          error_message: string | null;
          gas_used: string | null;
          gas_price: string | null;
          effective_gas_price: string | null;
          block_number: number | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          proposal_id: string;
          forum_id: string;
          agent_ens: string;
          status?: 'pending' | 'success' | 'failed';
          tx_hash?: string | null;
          error_message?: string | null;
          gas_used?: string | null;
          gas_price?: string | null;
          effective_gas_price?: string | null;
          block_number?: number | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          proposal_id?: string;
          forum_id?: string;
          agent_ens?: string;
          status?: 'pending' | 'success' | 'failed';
          tx_hash?: string | null;
          error_message?: string | null;
          gas_used?: string | null;
          gas_price?: string | null;
          effective_gas_price?: string | null;
          block_number?: number | null;
          created_at?: string;
          completed_at?: string | null;
        };
      };
      agent_metrics: {
        Row: {
          id: string;
          agent_id: string;
          messages_posted: number;
          proposals_made: number;
          votes_participated: number;
          forums_participated: number;
          successful_executions: number;
          failed_executions: number;
          total_gas_spent: string;
          total_volume_traded: string;
          times_in_majority: number;
          times_in_minority: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          messages_posted?: number;
          proposals_made?: number;
          votes_participated?: number;
          forums_participated?: number;
          successful_executions?: number;
          failed_executions?: number;
          total_gas_spent?: string;
          total_volume_traded?: string;
          times_in_majority?: number;
          times_in_minority?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          messages_posted?: number;
          proposals_made?: number;
          votes_participated?: number;
          forums_participated?: number;
          successful_executions?: number;
          failed_executions?: number;
          total_gas_spent?: string;
          total_volume_traded?: string;
          times_in_majority?: number;
          times_in_minority?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      agent_strategy: 'conservative' | 'moderate' | 'aggressive';
      agent_status: 'active' | 'idle' | 'offline';
      forum_status: 'active' | 'consensus' | 'executing' | 'executed' | 'expired';
      message_type: 'discussion' | 'proposal' | 'vote' | 'result' | 'system';
      proposal_status: 'voting' | 'approved' | 'executing' | 'rejected' | 'executed' | 'expired';
      vote_type: 'agree' | 'disagree';
      execution_status: 'pending' | 'success' | 'failed';
    };
  };
}
